# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pe7XW1rJCT5P4lLh3XsZLMDqWeS966b1
"""

import torch
print(torch.__version__)

if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU:{torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available. using cpu")

a = torch.empty(2,3)

type(a)

torch.zeros(2,3)

torch.ones(2,3)

torch.rand(2,3)



torch.manual_seed(100)
torch.rand(2,3)

torch.tensor([[1,2,3],[4,5,6]])

print("using arange ->",torch.arange(0,10,2))
print("using linspace ->", torch.linspace(0,10,10))
print("using eye ->", torch.eye(5))
print("using full ->", torch.full((3,3),5))

x = torch.tensor([[1,2,3],[4,5,6]])
x

x.shape

torch.empty_like(x)

torch.zeros_like(x)

torch.ones_like(x)

torch.rand_like(x)

x

x.dtype

torch.tensor([1.0,2.0,3.0],dtype = torch.int32)

torch.tensor([1,2,3],dtype = torch.float64)

x.to(torch.float32)

torch.rand_like(x, dtype = torch.float32)

x + 2

x - 2

x * 3

x / 3

(x * 100)//3

((x * 100)//3)%2

a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

a + b

a - b

a * b

a / b

a ** b

a % b

c = torch.tensor([1, -2, 3, -4])

d = torch.tensor([1.9, 2.3, 3.7, 4.4])

torch.abs(c)

torch.neg(c)

torch.round(d)

torch.ceil(d)

torch.floor(d)

torch.clamp(d, min=2, max=3)

e = torch.randint(size=(2,3), low =0, high=10, dtype=torch.float32)
e

torch.sum(e)

torch.sum(e, dim = 0)

torch.sum(e, dim=1)

torch.mean(e)

torch.mean(e, dim=0)

torch.median(e)

torch.max(e)
torch.min(e)

torch.prod(e)

torch.std(e)

torch.var(e)

torch.argmax(e)

torch.argmin(e)

f = torch.randint(size=(2,3), low=0, high=10)
 g = torch.randint(size=(3,2), low=0, high=10)

 print(f)
 print(g)

torch.matmul(f,g)

vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

torch.dot(vector1, vector2)

torch.transpose(f, 0, 1)

h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)

h

torch.det(h)

torch.inverse(h)

i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

i > j

i < j

i == j

i != j

i >= j

i <= j

k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

torch.log(k)

torch.exp(k)

torch.sqrt(k)

torch.sigmoid(k)

torch.softmax(k, dim=0)

torch.relu(k)

m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

m.add_(n)

m

torch.relu(m)

m.relu_()

m

a = torch.rand(2,3)

b = a

a[0][0] = 0

a

id(a)

id(b)

b = a.clone()

a

b

a[0][0] = 10

a

b

id(a)

id(b)

torch.cuda.is_available()

device = torch.device("cuda")

torch.rand((2,3), device = device)

a  =torch.rand(2,3)

a

a.to(device)

b = a.to(device)

b + 5

import time

size = 10000

matrix_cpu1 = torch.randn(size,size)
matrix_cpu2 = torch.randn(size,size)

start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
cpu_time = time.time() - start_time

print(f"Time on CPU : {cpu_time: .4f} seconds")

matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)
torch.cuda.synchronize()
gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time : .4f} seconds")

print("\nSpeedup (CPU time / GPU time):", cpu_time / gpu_time)

a = torch.ones(4,4)
a

a.reshape(2,2,2,2)

a.flatten()

b = torch.rand(2,3,4)

b

b.permute(2,0,1)

c = torch.rand(226,226,3)

c.unsqueeze(0).shape

d = torch.rand(1,20)
d.squeeze(0).shape

import numpy as np

a = torch.tensor([1,2,3])
a

b = a.numpy()

b

c = np.array([1,2,3])

c

torch.from_numpy(c)

