# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DFjk3U7Rsx82PeotRC3EdeWd16Eq0IKr
"""

from sklearn.datasets import make_classification
import torch

X, y = make_classification(
    n_samples = 10,
    n_features = 2,
    n_informative = 2,
    n_redundant = 0,
    n_classes = 2,
    random_state = 42
)

X

X.shape

y

y.shape

X = torch.tensor(X, dtype = torch.float32)
y = torch.tensor(y, dtype = torch.long)

from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):

  def __init__(self, features, labels):

    self.features = features
    self.labels = labels

  def __len__(self):

    return self.features.shape[0]

  def __getitem__(self, index):

    return self.features[index], self.labels[index]

dataset = CustomDataset(X, y)

from torch.utils.data import random_split

train_size = int(0.8 * len(dataset)) # 80% for training
test_size = len(dataset) - train_size # Remaining for testing

train_dataset, test_dataset = random_split(dataset, [train_size, test_size])

print(f"Training dataset size: {len(train_dataset)}")
print(f"Testing dataset size: {len(test_dataset)}")

len(dataset)

dataset[2]

dataloader= DataLoader(dataset, batch_size = 2, shuffle = False)

for batch_features, batch_labels in  dataloader:

  print(batch_features)
  print(batch_labels)
  print("-"*50)

train_loader = DataLoader(train_dataset, batch_size = 32, shuffle = True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

import torch.nn as nn
class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

learning_rate = 0.1
epochs = 25

model = MySimpleNN(X.shape[1])

optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

loss_function = nn.BCELoss()

for epoch in  range(epochs):

  for batch_features, batch_labels in train_loader:

    y_pred = model(batch_features)

    # Convert batch_labels to float32 as BCELoss expects float targets
    loss = loss_function(y_pred, batch_labels.view(-1,1).float())

    optimizer.zero_grad()

    loss.backward()

    optimizer.step()

  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

model.eval() # Set the model to evaluation mode

correct = 0
total = 0

with torch.no_grad(): # Disable gradient calculation during evaluation
  for batch_features, batch_labels in test_loader:
    outputs = model(batch_features)
    predicted = (outputs > 0.5).float() # Convert probabilities to binary predictions
    total += batch_labels.size(0)
    correct += (predicted == batch_labels.view(-1,1).float()).sum().item()

accuracy = 100 * correct / total
print(f'Accuracy of the model on the test dataset: {accuracy:.2f}%')

model.eval()

correct = 0
total = 0

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
      outputs = model(batch_features)
      predicted = (outputs>0.5).float()
      total += batch_labels.size(0)
      correct += (predicted == batch_labels.view(-1,1).float()).sum().item()

accuracy = 100*correct/total
print(f'Accuracy of the model on the test dataset: {accuracy: .2f}%')

