# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uw8tVx0trCj9yZmZPjtsipE7AZUzBXNk
"""

import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

df.shape

df.drop(columns=['id','Unnamed: 32'],inplace = True)

X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:],df.iloc[:, 0], test_size = 0.2)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

X_train

y_train

encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

y_train

X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

X_train_tensor.shape

y_train_tensor.shape

import torch.nn as nn
class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

learning_rate = 0.1
epochs = 25

loss_function = nn.BCELoss()

model = MySimpleNN(X_train_tensor.shape[1])

optimizer = torch.optim.SGD(model.parameters(),lr = learning_rate)

X_train_tensor = X_train_tensor.float()
y_train_tensor = y_train_tensor.float().unsqueeze(1)

for epoch in range(epochs):

       y_pred = model(X_train_tensor)

       loss = loss_function(y_pred, y_train_tensor)

       optimizer.zero_grad()

       loss.backward()

       optimizer.step()

       print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

model.linear.weight

X_test_tensor = X_test_tensor.float()
y_test_tensor = y_test_tensor.float().unsqueeze(1)

with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

